cloudflare/deploy.workers.cloudflare.com

app/src/App.js
app/src/components/configure.js

Show a different set of copy/buttons in the UI during the "Configure" section if a project requires Workers Bundled

Conditionally render configure UI based on paid

---

DEVELOPERS.md
README.md
worker/wrangler.toml

This PR updates the production URL for this project to https://deploy.workers.cloudflare.com.
The GitHub URLs have already been updated so I'll be merging this ASAP.
Closes #44

Update production URL

---

app/src/components/configure.js
app/src/components/deploy.js

- Fade images when step is complete
- Make images link
Closes #69, closes #68

Updates to example images in UI

---

app/src/App.js
app/src/components/completed.js

Make Workers logo a link

---

app/src/components/configure.js

Deep linking allows us to link to the plans page and a few other places.
So rad!
Closes #60
Closes #58

Add deep links in configure stage

---

app/src/components/completed.js

CSS improvements for completed page at small width

---

app/src/components/github-auth.js

@sgraden you mentioned "Bundle plan link" in the original issue, what is that in reference to?
Closes #57

Links should open in a new tab

---

app/package-lock.json
app/src/components/embed.js
app/tailwind.js

Colors for embed component

---

app/src/components/configure.js
app/src/components/deploy.js
app/src/components/subsection.js
app/src/index.css

Closes #65
---
@sgraden questions around color/logic here – should subsection states before _and_ after be a different color? also, what is that color? i looked in the color palette figma doc and couldn't find any info about the subsections being different colors so possible we both missed this :) i put this PR up to get the basics of the logic down but will make sure we lock it down before merging

Conditional blue/gray state for subsection badges

---

app/src/components/workflow-status.js
app/src/index.css

Use native SVG animation property to fix pulsing status dot
Closes #49

Fix status pulsing

---

app/public/success-graphic.svg
app/src/components/completed.js

Update completed page with new graphic and copy. Closes #66

Update completed page

---

app/package-lock.json
app/package.json
app/src/App.js
app/src/cache.js
app/src/components/deploy.js

Using lscache, expire anything stored in localstorage after an hour. If the lscache value is retrieved again (when a user refreshes or leaves and comes back to the app), the expiration gets bumped out again while re-accessing the value, to one hour from the current time.

Add localstorage cache expiration

---

app/src/components/deploy.js

Add override warning

---

app/src/App.js
app/src/components/completed.js
app/src/components/configure.js
app/src/components/deploy.js
app/src/components/github-auth.js
app/src/components/missing-url.js
app/src/components/sidebar.js

Mostly just some content updates! Should be inline with this doc https://docs.google.com/document/d/1BsYWykVzI1hWE8nlzNruAJ7KAXG8UNboaBWQ3fOPhko/edit?pli=1#heading=h.otgy0jbpcxlu

Raden text updates

---

app/src/App.js
app/src/components/completed.js
app/src/components/configure.js
app/src/components/workflow-status.js

added completed title into workflow-status and it updates with the status. Made the status icon element a link to Github Actions
Examples

Raden complete title changes

---

app/src/components/completed.js

Here is the restart button branch - Seems to have a merge issue. Looking to add a confirmation of leaving modal like this, but not super sure how to do that :D Tailwind have something for it?

Raden restart button

---

app/src/components/embed.js
app/src/components/missing-url.js
app/src/components/sidebar.js
app/src/components/templates.js
app/src/index.css

Template refresh

---

app/src/App.js

fixes https://github.com/cloudflare/deploy.workers.cloudflare.com/runs/1487600212?check_suite_focus=true#step:6:27

fix: remove useless escape

---

app/src/App.js
app/src/components/completed.js
app/src/components/missing-url.js
worker/workers-site/index.js
worker/wrangler.toml

Validate query param and document.cookie security improvements

---

src/components/embed.js

Update to use https://mbed.developers.workers.dev

Update mbed deploy

---

functions/callback.ts
functions/secret.ts
helpers/validateCookie.ts
src/App.js
src/components/github-auth.js
src/components/templates.js

this PR fixes 
- the redirect to homepage once users go through the GitHub oauth flow, and completely losing the state (need to navigate back to the repository and click the button again)
- fills one empty spot - adding status page project 👼

fix missing state and fill missing space 

---

src/components/templates.js

https://landing-page-link.deploy-workers-cloudflare-com.pages.dev/

link to deploy flow from landing page

---

src/App.js
src/components/configure-account.js

MOW-103: support API token template
